{"errorType":"TypeError","errorMessage":"fetch failed","trace":["TypeError: fetch failed","    at node:internal/deps/undici/undici:13510:13","    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","    at async exports.handler (/var/task/taskcafe-wrapper.js:45:22)"]}